export const indianJobs = [
  {
    id: 1,
    title: 'Civil Helper',
    position: '200',
    pay: 'Rs30,000',
    location: 'Delhi',
    image: '/images/constru1.png',
    type: 'India',
  },
  {
    id: 2,
    title: 'Civil Supervisor',
    position: '10',
    pay: 'Rs30,000',
    location: 'Bangalore',
    image: '/images/con.sup2.png',
    type: 'India',
  },
  {
    id: 3,
    title: 'Handyman',
    position: '10',
    pay: 'Rs30,000',
    location: 'Kolkata',
    image: '/images/handyman servies.jpeg',
    type: 'India',
  },
  {
    id: 4,
    title: 'Fitter',
    position: '10',
    pay: 'Rs30,000',
    location: 'Hyderabad',
    image: '/images/mason-tile installer1.png',
    type: 'India',
  },
  {
    id: 5,
    title: 'Logistics Supervisor',
    position: '2',
    pay: 'Rs30,000',
    location: 'Ahmedabad',
    image: '/images/driver.jpeg',
    type: 'India',
  },
  {
    id: 6,
    title: 'Logistics & Warehouse Helper',
    position: '10',
    pay: 'Rs30,000',
    location: 'Chennai',
    image: '/images/driver.jpeg',
    type: 'India',
  },
  {
    id: 7,
    title: 'Electrician',
    position: '15',
    pay: 'Rs30,000',
    location: 'Jaipur',
    image: '/images/handyman servies.jpeg',
    type: 'India',
  },
  {
    id: 8,
    title: 'Masons',
    position: '10',
    pay: 'Rs30,000',
    location: 'Lucknow',
    image: '/images/mason-tile installer1.png',
    type: 'India',
  },
  {
    id: 9,
    title: 'Plumbers',
    position: '10',
    pay: 'Rs30,000',
    location: 'Pune',
    image: '/images/handyman servies.jpeg',
    type: 'India',
  },
  {
    id: 10,
    title: 'Warehouse Operators',
    position: '10',
    pay: 'Rs30,000',
    location: 'Nagpur',
    image: '/images/constru1.png',
    type: 'India',
  },
  {
    id: 11,
    title: 'Housekeeping',
    position: '50',
    pay: 'Rs30,000',
    location: 'Mumbai',
    image: '/images/cook1.png',
    type: 'India',
  },
  {
    id: 12,
    title: 'Security Guards',
    position: '20',
    pay: 'Rs30,000',
    location: 'Nashik',
    image: '/images/gardener1.png',
    type: 'India',
  },
];

export const overseasJobs = [
  {
    id: 13,
    title: 'Civil Helper',
    position: '50',
    pay: 'AED 1500',
    location: 'Dubai',
    image: '/images/constru1.png',
    type: 'overseas',
  },
  {
    id: 14,
    title: 'Electrician',
    position: '10',
    pay: 'AED 1800',
    location: 'Abu Dhabi',
    image: '/images/handyman servies.jpeg',
    type: 'overseas',
  },
  {
    id: 15,
    title: 'Logistics & Warehouse Helper',
    position: '20',
    pay: 'AED 1800',
    location: 'Sharjah',
    image: '/images/driver.jpeg',
    type: 'overseas',
  },
  {
    id: 16,
    title: 'Plumbers',
    position: '10',
    pay: 'AED 1800',
    location: 'Qatar',
    image: '/images/handyman servies.jpeg',
    type: 'overseas',
  },
  {
    id: 17,
    title: 'Security Guards',
    position: '10',
    pay: 'AED 1900',
    location: 'Ajman',
    image: '/images/gardener1.png',
    type: 'overseas',
  },
];
