export const indianJobs = [
  {
    id: 1,
    title: 'Civil Helper',
    position: '200',
    // pay: 'Rs30,000',
    location: 'Delhi',
    image: '/images/constru1.png',
    type: 'India',
  },
  {
    id: 2,
    title: 'Civil Supervisor',
    position: '10',
    // pay: 'Rs30,000',
    location: 'Bangalore',
    image: '/images/con_sup3.png',
    type: 'India',
  },
  {
    id: 3,
    title: 'Handyman',
    position: '10',
    // pay: 'Rs30,000',
    location: 'Kolkata',
    image: '/images/handyman servies.jpeg',
    type: 'India',
  },
  {
    id: 4,
    title: 'Carpenter',
    position: '50',
    // pay: 'Rs30,000',
    location: 'Pune',
    image: '/images/carp1.png',
    type: 'India',
  },
  {
    id: 5,
    title: 'Logistics Supervisor',
    position: '2',
    // pay: 'Rs30,000',
    location: 'Ahmedabad',
    image: '/images/manufacutring and industrial.png',
    type: 'India',
  },
  {
    id: 6,
    title: 'Logistics & Warehouse Helper',
    position: '10',
    // pay: 'Rs30,000',
    location: 'Chennai',
    image: '/images/logistics and transport.png',
    type: 'India',
  },
  {
    id: 7,
    title: 'Electrician',
    position: '15',
    // pay: 'Rs30,000',
    location: 'Jaipur',
    image: '/images/elec1.png',
    type: 'India',
  },
  {
    id: 8,
    title: 'Masons',
    position: '10',
    // pay: 'Rs30,000',
    location: 'Lucknow',
    image: '/images/mason-tile installer1.png',
    type: 'India',
  },
  {
    id: 9,
    title: 'Plumbers',
    position: '10',
    // pay: 'Rs30,000',
    location: 'Pune',
    image: '/images/plumber1.png',
    type: 'India',
  },
  {
    id: 10,
    title: 'Construction Workers',
    position: '50',
    // pay: 'Rs30,000',
    location: 'Nagpur',
    image: '/images/constru1.png',
    type: 'India',
  },
  {
    id: 11,
    title: 'Housekeeping',
    position: '50',
    // pay: 'Rs30,000',
    location: 'Mumbai',
    image: '/images/housekeeping.png',
    type: 'India',
  },
  {
    id: 12,
    title: 'Gardener',
    position: '5',
    // pay: 'Rs30,000',
    location: 'Nashik',
    image: '/images/gardener1.png',
    type: 'India',
  },
];

export const overseasJobs = [
  {
    id: 13,
    title: 'Civil Helper',
    position: '50',
    pay: 'AED 1500',
    location: 'Dubai',
    image: '/images/constru2.png',
    type: 'overseas',
  },
  {
    id: 14,
    title: 'Electrician',
    position: '10',
    // pay: 'AED 1500',
    location: 'Abu Dhabi',
    image: '/images/elec1.png',
    type: 'overseas',
  },

    {
    id: 15,
    title: 'Carpenter',
    position: '50',
    // pay: 'AED 1500',
    location: 'Dubai',
    image: '/images/carpenter.jpeg',
    type: 'overseas',
  },

  {
    id: 16,
    title: 'Logistics & Warehouse Helper',
    position: '20',
    // pay: 'AED 1800',
    location: 'Sharjah',
    image: '/images/logistics and transport.png',
    type: 'overseas',
  },
  {
    id: 17,
    title: 'Plumbers',
    position: '10',
    // pay: 'AED 1800',
    location: 'Dubai',
    image: '/images/handyman servies.jpeg',
    type: 'overseas',
  },
  {
    id: 18,
    title: 'Gardeners',
    position: '10',
    // pay: 'AED 1900',
    location: 'Dubai',
    image: '/images/gardener1.png',
    type: 'overseas',
  },
];
